In [1]:
import tensorflow as tf

2023-03-25 21:33:35.201604: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-25 21:33:35.241459: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-03-25 21:33:35.433644: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-03-25 21:33:35.435085: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-25 21:33:36.917417: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [2]:
a = tf.constant(10)
b = tf.constant(3)
c=a+b
c

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [3]:
a1 = tf.constant([[3,3]])
a2 = tf.constant([[3],[3]])
res = tf.matmul(a1,a2)
res
res.numpy()

array([[18]], dtype=int32)

In [4]:
c.numpy()

13

In [5]:
var1 = tf.Variable(100)
var2 = tf.Variable(3)
sum = tf.add(var1,var2)
sum.numpy()

103

In [6]:
assign = var1.assign(2)
assign.numpy()
var1.numpy()


2

In [7]:
sum.numpy()

103

In [8]:
import numpy as np
import tensorflow as tf
from keras.datasets import mnist
from keras.datasets.mnist import input_data

ImportError: cannot import name 'input_data' from 'keras.datasets.mnist' (/home/pranjal/.local/lib/python3.11/site-packages/keras/datasets/mnist.py)

In [ ]:
def run_cnn():
    mnist = input_data.read_data("MNIST_data/", one_hot = True)
    learning = 0.0001
    epochs = 10
    batch_size = 50
    

In [ ]:

x = tf.placeholder(tf.float32, [None,784])
x_shaped = tf.reshape(x,[-1,28,28,1])
y = tf.placeholder(tf.float32, [None,10])


In [10]:
t = tf.zeros([5,5,5,5])
t

<tf.Tensor: shape=(5, 5, 5, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

  

In [ ]:
from keras import tensorflow_hub as hub
feature_extractor_url = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/2"
feature_extractor_layer = hub.KerasLayer()